### ISSUE TITLE
Chats appearing in wrong chat rooms

### ISSUE THREAD

**Issue by mrigsbee** [Alec-Nelson/GobblerExchange#11]
When in the 4704 chat, if Alec posts in All, I can see his post in 4704 chat. Then if I go to All then back to 4704, his post isn't there anymore (just in All).

**Comment by mjwabby** [comment]
Edit: megan made a new issue for what i was saying, ignore me.

**Comment by mrigsbee** [comment]
I opened a separate issue for that. I'm closing this one.
