### ISSUE TITLE
Tabs not highlighted in sub-menus

### ISSUE THREAD

**Issue by mjwabby** [Alec-Nelson/GobblerExchange#13]
As discussed during the meeting, the navigation tags aren't highlighted when in "sub-menus",  like viewing individual notes or on edit menus.

**Comment by kaityblohm** [comment]
Alright, I'm pretty sure I fixed them all, can someone double check to make sure I didn't miss any so I can close this?

**Comment by mrigsbee** [comment]
The only one missing is Calendar isn't highlighted when editing a calendar event.

**Comment by kaityblohm** [comment]
ah yes, thanks for finding that, just pushed the fix for that so I'm going to go ahead and close this
