### ISSUE TITLE
Error Message at top of Notes View Comment

### ISSUE THREAD

**Issue by kaityblohm** [Alec-Nelson/GobblerExchange#14]
So I went to the notes page and clicked on the the view comments button and it went to the right page and then this error appeared at the top.  I attached a screenshot below.  I haven't seen it appear on any pages so far.  Also since it's a little hard to read, this is the error itself

Notice: Undefined property: Notes::$tag in C:\xampp\htdocs\GobblerExchange\app\model\DbObject.class.php on line 18

![image](https://cloud.githubusercontent.com/assets/7155049/24731563/f48523e0-1a38-11e7-9535-b679ab9a9c36.png)

**Comment by mrigsbee** [comment]
Just pushed a fix, check it now

**Comment by kaityblohm** [comment]
gone now!
