### ISSUE TITLE
Notes can be submitted with no title

### ISSUE THREAD

**Issue by szuzzah** [Alec-Nelson/GobblerExchange#16]
This should probably be disallowed, as it prevents people from opening the file since you click on the name to open it.

**Comment by alexlamon** [comment]
^^ You can create a new group without a CRN or Group Name as well

**Comment by mrigsbee** [comment]
Checking for empty fields is on the README as unimplemented. Make sure to only look at the implemented stuff for debugging.

**Comment by Alec-Nelson** [comment]
fixed this in a0ede8e10ef86ad1c6b6aadba19aac88ac9f90ef
