### ISSUE TITLE
Sorting forum posts

### ISSUE THREAD

**Issue by alexlamon** [Alec-Nelson/GobblerExchange#18]
Forum posts are automatically sorted by popularity (points) and, if they have same number of points, date. However, the dropdown is automatically set to sort by date yet this sorting method seems to be by popularity. 

Also, the dropdown doesn't seem to actually do anything -- you can't change sorting method from popularity to date.

**Comment by Alec-Nelson** [comment]
I'm currently working on this.

**Comment by Alec-Nelson** [comment]
completed in 3f02bc82422cfa4e97a90d87391c376741aaffaf
