### ISSUE TITLE
Calendar event issue with date always being 01/03/2019

### ISSUE THREAD

**Issue by kaityblohm** [Alec-Nelson/GobblerExchange#2]
When a calendar event is created, the date seems to always end up being 01/03/2019 no matter what date you put in to begin with

**Comment by mrigsbee** [comment]
Was this the same problem with not entering the date in the format yyyy-mm-dd?

**Comment by kaityblohm** [comment]
I believe so, the problem was fixed when I put the date into the right format.  I will add a few more events later this afternoon to be sure, but I think that's what the problem was
