### ISSUE TITLE
Error when searching

### ISSUE THREAD

**Issue by alexlamon** [Alec-Nelson/GobblerExchange#21]
Every time I try to complete a search using the Forum search bar, I get an error overlaying the dropdown that sorts the posts. It says "Undefined variable: sortType in /Applications/XAMPP/xamppfiles/htdocs/GobblerExchange/app/view/forum.html on line 45"

**Comment by Alec-Nelson** [comment]
I think I fixed the issue with 619e1d2057d7fa56640d7053d656f2190b2943f0 let me know if you are still getting the issue.

**Comment by alexlamon** [comment]
It works!
