### ISSUE TITLE
Forum Post Searching- doesn't see tags

### ISSUE THREAD

**Issue by kaityblohm** [Alec-Nelson/GobblerExchange#22]
I created a post in the forum with a tag of project.  I then used the search bar on the forum page and searched for project and since project was only part of the tag, no posts appeared.  I could be wrong, but I figured we would want the user to be able to find a post based on the tag

**Comment by Alec-Nelson** [comment]
The use case for searching the forum, involved finding specific forum posts. So I have only implemented searching for the title and description of a forum post.
