### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by alexlamon** [Alec-Nelson/GobblerExchange#24]
You can't open a note on the main Notes page, you have to click "View Comments" in order to click the link and open the note.

**Comment by mrigsbee** [comment]
Just pushed the fix for the bug. Should work on local. I'll have @Alec-Nelson update the AWS site soon.

**Comment by mjwabby** [comment]
Is this also the case for notes not uploading properly? I tried uploading some notes on AWS (in the Harry Potter group) and they're 404ing. Uploading seems to work on local, so I'm not sure if this is just that the AWS is out of date, or if theres an AWS-specific issue since the file systems are different.

**Comment by mrigsbee** [comment]
send me the PDFs over email and I'll take a look

**Comment by mjwabby** [comment]
I mean, its not a specific pdf issue, as far as i can tell. I just tried downloading one of the files that was properly on the AWS version (the "yoooo"/'test3.pdf" on the HP class), and reuploading it under a new name, and that also failed, so its not anything about individual pdfs

**Comment by mrigsbee** [comment]
Should work now. We forgot to change directory permissions in AWS. I'll remove all notes that didn't get uploaded, but all new ones should work now.

**Comment by mjwabby** [comment]
Yeah, just did a quick test and it worked.

**Comment by mrigsbee** [comment]
Awesome. We'll check again once we do the update just to be positive we didn't mess it up again. Thanks for finding that. That was a pretty huge bug.
