### ISSUE TITLE
Can't add multiple calendar events

### ISSUE THREAD

**Issue by kaityblohm** [Alec-Nelson/GobblerExchange#3]
I tried to add a second calendar event but only the first one was ever displayed

**Comment by mrigsbee** [comment]
What was the date & time of the event?

**Comment by kaityblohm** [comment]
which event? the first one I added or the second one I attempted to add?

**Comment by mrigsbee** [comment]
both so I can replicate your input

**Comment by kaityblohm** [comment]
oh wait never mind, I think because I was putting in the date in the wrong order (I did year then day then month) it was maybe not creating the event, or doing something weird with the event, but if I do the dates correctly then it seems to work fine.  My bad about that haha for like the final product though we may want to do something different as far as typing in the date (or have like ways to tell the user they did it wrong), so that doesn't cause problems

**Comment by mrigsbee** [comment]
That's a good idea. I used DatePicker before: [https://jqueryui.com/datepicker/]
That way we don't have to worry about all the various formats the user can enter the date since it'll save their pick as the same format. What do you think about using this for the next deliverable?

**Comment by kaityblohm** [comment]
yeah I think that would work great!  definitely a lot easier for users and will hopefully keep issues like what I described from happening
