### ISSUE TITLE
Creating a new group

### ISSUE THREAD

**Issue by kaityblohm** [Alec-Nelson/GobblerExchange#5]
When I first tried to add a class to my profile, the form came up where I could fill in the CRN and then once I submitted the information, the class did not appear.  I used the CRN for the Capstone class 12624.  Which I'm assuming is just because we haven't gotten the scraping of the timetable yet.  But also, after trying to submit one group, if I click the button to create another group, the form isn't pulled up and nothing happens

**Comment by mjwabby** [comment]
Huh...i apparently messed up when i was making some changes earlier today. Or rather, when i was syncing my changes, cause they don't seem to exist anymore, or have a commit or anything. Luckily that was just some minor stuff, but thats (i think) why the crn isn't working. To clarify, this was all one thing? Like you tried to add via CRN and then the form was broken? When you say the form isn't pulled up, do you mean you hit the button and nothing happens, it stays on the same page with no error message or anything? Were you making a group with a duplicate name? If so, then i think thats the same issue; when i pushed the first crn/json stuff, i messed with the error dialogues, and the commit where i put it back was that one i just mentioned i messed up somehow.

**Comment by kaityblohm** [comment]
yeah so when I tried to add via CRN it went back to like the main view you see when you first log in with no new group created, and no message saying that like it already existed.  And then when I tried to create another group, it didn't do anything, stayed on the same page with no error message and it didn't give me the view with input fields to try a new CRN.

**Comment by kaityblohm** [comment]
I also just tried logging out and logging back in again in the hopes that it would reset, but the create a group button doesn't do anything when it's pushed anymore for me

**Comment by mjwabby** [comment]
Hmm...was this on the AWS version or on XAMPP?

**Comment by kaityblohm** [comment]
aws

**Comment by mjwabby** [comment]
Hmm...that's weird; trying to add that CRN on aws for me doesn't add it, but it does give an error...Oh, nevermind, i see it now. I'm still not sure why the form disabled itself, since it didn't for me, but the other issues should be fixed in the commit i'm about to push.

**Comment by mjwabby** [comment]
If you can still replicate the issue on AWS, can you send a screenshot of what the form-error looks like? (full screenshot of page, not snipping tool) I can't see how the fixes i just pushed would have fixed an error like that, but i don't want to wait until megan can update the AWS to confirm that.

**Comment by kaityblohm** [comment]
have you pushed?/do you want me to pull? or do you want me to just take a screenshot now?

**Comment by mjwabby** [comment]
I've pushed, but that doesn't change the AWS version, so i'd like a screenshot of whats happening on AWS so i can see if i can replicate it and find out what the issue is, and then i'd like you to try what you were trying before on the XAMPP version to see if my fixes fixed everything else you were dealing with.

**Comment by kaityblohm** [comment]
![image](https://cloud.githubusercontent.com/assets/7155049/24437263/08ad3df2-140e-11e7-9aaa-d3e53d6e899f.png)


Here's a screen shot right after I tried to press the create a group button.

**Comment by kaityblohm** [comment]
I tried the same thing on XAMPP and that worked fine for adding a CRN.  However, I then tried to add a group and it gave me an error message and said it wasn't a valid CRN (didn't check the box that asked if it was a class)  here's a screen shot below, I tried to name the group Testing

![image](https://cloud.githubusercontent.com/assets/7155049/24437417/f0612d3e-140e-11e7-8fe5-716724ba1b1e.png)

**Comment by mjwabby** [comment]
Oh, i misunderstood the issue. I thought the two things came from the same thing (adding via crn). Yeah, i can duplicate this easily on AWS now, by adding via name instead of crn...hmm. I certainly can add via name on my local version without issue, after i fixed a minor issue in my previous commit, so i'm not sure... I'll assign megan to the task since i think she's the only one who knows the AWS info and can update it?

**Comment by mjwabby** [comment]
Yeah that issue on xampp is the one i just fixed and pushed, sorry. Messed up an if.

**Comment by mrigsbee** [comment]
If it works on local, that's fine as far as making sure the bug is fixed. Use the local as the most up-to-date version for finding/fixing bugs. I already updated AWS earlier this evening, so I'll update AWS again tomorrow evening (before deliverable 3 is due).

**Comment by mjwabby** [comment]
Sounds good then. I'll let kaity close the issue, in case there's something else wrong on the xampp version after my changes that i haven't found in my testing?

**Comment by kaityblohm** [comment]
I got a little confused in some of your responses, so did you fix the issue where if you try to enter a group name instead of just a CRN in tells you that it's not a valid CRN?

**Comment by mjwabby** [comment]
I believe i did, and its working for me at least, with a second commit, yes (The "very quick fix").

**Comment by kaityblohm** [comment]
just pulled and tried again and it worked!  I'll go ahead and close this now
