### ISSUE TITLE
Weird register-login issue

### ISSUE THREAD

**Issue by mjwabby** [Alec-Nelson/GobblerExchange#6]
Registering, on both the AWS build and the current git build, succeeds silently and stays on the login page. From the comments in the site controller, it should redirect to the home page but doesn't. Also, theres a "Success" session variable used there and a couple other places that doesn't seem to ever be used/echoed anywhere.

**Comment by mjwabby** [comment]
So this seems to be a much wider issue than i thought. Biggest issue: Some people/methods use the "username" session variable to handle who is logged in, and others use the "userid" session variable. 
Among other things, this means that if you register ("test"), then log in as a different preexisting user ("mjwabby") like i accidentally did, then everything is borked and it tries to take me to the home page in the form of the viewgroup page of a group that mjwabby belongs to, but the username variable is set to 'test' and the userid variable is set to nothing, so i keep getting issues. and since the base url redirects that same way, i can't even sign out.

**Comment by mjwabby** [comment]
The 'fails silently" issue is easy to fix, and i'll push a change fixing that in a second, but it wont fix the issue i just described. While thats admittedly a rare scenario, i'm almost certain there will be other issues as well from the inconsistency. Just going off the search i just ran through my files, there was a check regarding comments using ['username'], and i dont think thats set by anything other than registering, which means any tests might have worked while the variable was still set properly but will fail otherwise.

**Comment by mjwabby** [comment]
I'm not sure how the notifications for these work, so i changed the name to get more attention and i'm sending this to make sure another email goes out with the new more accurate name. Sorry for the email spam.

**Comment by mrigsbee** [comment]
It's just not updated yet. We're using userId for the user's session var, not username. It's not updated completely from last semester's code yet. We're still phasing it out.

**Comment by Alec-Nelson** [comment]
I've already fixed logging in after registering. All current log in checks utilize the userId session variable.  Where are you seeing login checks that utilize username as a session variable?

**Comment by mjwabby** [comment]
I mean, in terms of using $_SESSION['username'] in general? sublime says we're using it 11 times, though i think home.tpl isn't being used aymore so 10? And if template.tpl is also out of date, 7? 
CalendarController:212, CommentController:121 and 170, NotesController:279, and PollController:217 all use it, it looks like?
And if you've fixed it, it hasn't been synced, because i haven't been able to get my local copy fixed. Even logging in again gives me an error about accessing protected properties.

**Comment by mrigsbee** [comment]
We're phasing it out. Where you see it is places where we haven't completed implementation. Notice the README file says that we haven't implemented ensuring that only the user who's the author may edit/delete notes/polls/comments/etc. Those are the places you're seeing the username session variable being used.
Also, yes, home.tpl isn't being used. Template.tpl is not out of date.

**Comment by mrigsbee** [comment]
Don't look at the code for debugging since you might run into places where we haven't implemented something in its entirety. You should be looking for bugs in the website itself. If something is acting funny, check the README file to make sure we have implemented it, then let us know what needs to be fixed.

**Comment by Alec-Nelson** [comment]
What error specifically are you getting from "logging in again"?
Do you have the most up to date sql file?

**Comment by mjwabby** [comment]
Ok, that makes sense--though if i'm reading this right, we currently don't allow anyone to edit anything, as opposed to allowing everyone to do so; that's part of why i was confused. I can't confirm that, though, because i still can't get anything to work on my local copy.

I'm headed to bed, and hopefully its an issue with the session variables and i think those will expire overnight, but just to clarify the issue in case you can replicate it:

I registered a new user, "t" while testing the original minor issue i thought i'd found. 
This put me back at the login screen, so i logged in (without refreshing the page or anything), and instinctively typed in the user i'd been doing testing with, "mjwabby".
This led me to the home page for mjwabby, viewing a group that user had joined (in this case, group id 5). However, the userid session variable was not set, for some reason, so the page mostly just displayed an error about that (and another error from it trying to get information from the user object it was supposed to find with that id).
Then, if i try logging in again, it errors out on the postlogin page with "Fatal error: Cannot access protected property Group::$group_name in C:\xampp\htdocs\GobblerExchange\app\controller\SiteController.php on line 88",
I've tried modifying template.php to show the signout button and signing out, i've tried registering new users, i've tried logging in again, and it won't change. I'm using the most recent version of the code, with the only difference other than temporary modifications for debugging being an extra use of session-error messages.

**Comment by gdcolella** [comment]
This issue from line 88 is likely from my code, I'll take a look at it
