### ISSUE TITLE
AWS same-day event error.

### ISSUE THREAD

**Issue by mjwabby** [Alec-Nelson/GobblerExchange#7]
Events that are scheduled for later in the day don't show up on AWS, but do on Local. Instead, it redirects back to the calendar page without any change or error message. There should be 2 or 3 attempts to create an event in the capstone group for Deliverable 3 in the SQL, assuming it edited the SQL but isn't showing it..

**Comment by mrigsbee** [comment]
Can you check now? I had to update the timezone since Amazon's default isn't our timezone. Close the issue if it's fixed.

**Comment by mjwabby** [comment]
Looks like it works!
