### ISSUE TITLE
Finalize Tags

### ISSUE THREAD

**Issue by mrigsbee** [Alec-Nelson/GobblerExchange#9]
We need to finalize what tags we want to use. They need to be generic enough to be used for class-related groups and non-class-related groups. Some I think are good are:
- homework
- project
- exam/test
- notes
- question/help
- meeting/meet up
- discussion
- other (catch-all)

What others do you guys want? Should we change any of the suggestions in my list?

**Comment by mjwabby** [comment]
What's the difference between exam and test here? Also, maybe "discussion"?

**Comment by mrigsbee** [comment]
Lol good call, I updated that issue and added your suggestion

**Comment by mjwabby** [comment]
Cool. Only other thing i can think of is if we want a tag specifically for like silly things? Cause if this were actually being used, there would definitely be posts with memes or the like, the only question is whether we'd want to actually have a "funny" tag or the like.

**Comment by kaityblohm** [comment]
Couldn't they then just use the other tag?

**Comment by mrigsbee** [comment]
Implemented updated tags!
